using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text.RegularExpressions;
using UnityEngine.Serialization;

namespace Framework.EditorScripts
{
	public class FieldNamingStandardizerWindow : EditorWindow
	{
		private DefaultAsset folder;
		private MonoScript singleScript;

		[MenuItem("Tools/Code/Field Naming Standardizer")]
		public static void Open()
		{
			GetWindow<FieldNamingStandardizerWindow>("Field Naming Standardizer");
		}

		private void OnGUI()
		{
			GUILayout.Label("Industry Standard Field Naming", EditorStyles.boldLabel);
			GUILayout.Space(10);

			singleScript = EditorGUILayout.ObjectField(
				"Single Script",
				singleScript,
				typeof(MonoScript),
				false
			) as MonoScript;

			folder = EditorGUILayout.ObjectField(
				"Folder (Batch)",
				folder,
				typeof(DefaultAsset),
				false
			) as DefaultAsset;

			GUILayout.Space(10);

			if (GUILayout.Button("Apply Naming Rules"))
			{
				if (singleScript != null)
				{
					ProcessFile(AssetDatabase.GetAssetPath(singleScript));
				}

				if (folder != null)
				{
					string path = AssetDatabase.GetAssetPath(folder);
					ProcessFolder(path);
				}

				AssetDatabase.Refresh();
				Debug.Log("✔ Field naming standardization complete.");
			}
		}

		private void ProcessFolder(string folderPath)
		{
			string absolute = Application.dataPath.Replace("Assets", "") + folderPath;
			var files = Directory.GetFiles(absolute, "*.cs", SearchOption.AllDirectories);

			foreach (var file in files)
				ProcessFile(file);
		}

		private void ProcessFile(string filePath)
		{
			string code = File.ReadAllText(filePath);

			// Skip auto-generated
			if (code.Contains("<auto-generated"))
				return;

			// Match fields only (not properties)
			Regex fieldRegex = new Regex(
				@"(\[SerializeField\]\s*)?(public|private|protected)\s+([\w<>]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*;",
				RegexOptions.Multiline
			);

			code = fieldRegex.Replace(code, match =>
			{
				bool isSerialized = match.Groups[1].Success;
				string access = match.Groups[2].Value;
				string type = match.Groups[3].Value;
				string oldName = match.Groups[4].Value;

				string newName = GetNewName(access, isSerialized, oldName);

				if (oldName == newName)
					return match.Value;

				string formerly =
					isSerialized
					? $"[FormerlySerializedAs(\"{oldName}\")]\n    "
					: "";

				return $"{formerly}{(isSerialized ? "[SerializeField]\n    " : "")}{access} {type} {newName};";
			});

			File.WriteAllText(filePath, code);
		}

		private string GetNewName(string access, bool serialized, string name)
		{
			// Public
			if (access == "public")
				return ToPascal(name);

			// Protected
			if (access == "protected")
				return ToPascal(name);

			// Private or Serialized
			return "_" + ToCamel(name.TrimStart('_'));
		}

		private string ToPascal(string input)
		{
			input = input.TrimStart('_');
			return char.ToUpper(input[0]) + input.Substring(1);
		}

		private string ToCamel(string input)
		{
			return char.ToLower(input[0]) + input.Substring(1);
		}
	}
}
