using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text.RegularExpressions;

namespace Framework.EditorScripts
{
	public class NamespaceChangerWindow : EditorWindow
	{
		private DefaultAsset folder;
		private string newNamespace = "MyNamespace";

		[MenuItem("Tools/Namespace Replacer")]
		public static void Open()
		{
			GetWindow<NamespaceChangerWindow>("Namespace Replacer");
		}

		private void OnGUI()
		{
			GUILayout.Label("Namespace Replacer Tool", EditorStyles.boldLabel);

			folder = EditorGUILayout.ObjectField("Select Folder", folder, typeof(DefaultAsset), false) as DefaultAsset;
			newNamespace = EditorGUILayout.TextField("New Namespace", newNamespace);

			GUI.enabled = folder != null && !string.IsNullOrEmpty(newNamespace);

			if (GUILayout.Button("Apply Namespace"))
			{
				string folderPath = AssetDatabase.GetAssetPath(folder);
				ReplaceInFolder(folderPath);
				AssetDatabase.Refresh();
			}

			GUI.enabled = true;
		}

		private void ReplaceInFolder(string folderPath)
		{
			string absolutePath = Path.Combine(
				Application.dataPath.Replace("Assets", ""),
				folderPath
			);

			string[] files = Directory.GetFiles(absolutePath, "*.cs", SearchOption.AllDirectories);

			foreach (string file in files)
			{
				FixNamespace(file);
			}

			Debug.Log("Namespace update complete!");
		}

		private void FixNamespace(string filePath)
		{
			string code = File.ReadAllText(filePath);

			// Skip auto-generated files
			if (code.Contains("<auto-generated"))
				return;

			// Detect existing namespace
			Regex namespaceRegex = new Regex(
				@"namespace\s+[A-Za-z0-9_.]+\s*\{",
				RegexOptions.Multiline
			);

			if (namespaceRegex.IsMatch(code))
			{
				// ✅ Replace existing namespace
				code = namespaceRegex.Replace(code, $"namespace {newNamespace}\n{{", 1);
			}
			else
			{
				// ✅ Extract using statements
				MatchCollection usingMatches = Regex.Matches(
					code,
					@"^\s*using\s+[A-Za-z0-9_.]+;\s*$",
					RegexOptions.Multiline
				);

				string usingBlock = "";
				foreach (Match m in usingMatches)
					usingBlock += m.Value + "\n";

				// Remove using statements from original code
				code = Regex.Replace(
					code,
					@"^\s*using\s+[A-Za-z0-9_.]+;\s*$",
					"",
					RegexOptions.Multiline
				).TrimStart();

				// Wrap with namespace
				code =
$@"{usingBlock}
namespace {newNamespace}
{{
{Indent(code)}
}}";
			}

			File.WriteAllText(filePath, code);
		}

		private string Indent(string code)
		{
			return Regex.Replace(code, "^", "    ", RegexOptions.Multiline);
		}
	}
}
